[project]
name = "orbit-display-oled-128x32-yd-esp32-s3"
version = "0.1.0"
description = "Orbit OLED 128x32 YD-ESP32-S3 firmware"
requires-python = ">=3.13"
dependencies = [
    "grpcio-tools==1.83.1",
    "nanopb==0.4.9.1",
    "platformio==6.1.19",
    "pytest==8.4.2",
    "pyyaml==6.0.3",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = [".", "scripts"]
