# /// script
# dependencies = ["fonttools==4.60.1", "pillow==12.0.0"]
# ///
"""Run with `uv run nodes/app/tool/generate_icons.py /path/to/flutter`.

Reuse the homepage's Material icon for all launcher assets.
"""

import re
import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

app = Path(__file__).resolve().parents[1]
sdk = Path(sys.argv[1])
icons = (sdk / "packages/flutter/lib/src/material/icons.dart").read_text()
codepoint = int(re.search(r"blur_circular_rounded = IconData\((0x[0-9a-f]+)", icons)[1], 16)
font_path = sdk / "bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf"
foreground, background = "#26352F", "#FAFBF9"

# Extract the same glyph as a vector for Android's adaptive and themed icons.
font = TTFont(font_path)
glyphs = font.getGlyphSet()
glyph = glyphs[font.getBestCmap()[codepoint]]
bounds = BoundsPen(glyphs)
glyph.draw(bounds)
x0, y0, x1, y1 = bounds.bounds
scale = 60 / max(x1 - x0, y1 - y0)
pen = SVGPathPen(glyphs, ntos=lambda n: f"{n:.4f}".rstrip("0").rstrip(".") if n else "0")
glyph.draw(TransformPen(pen, (scale, 0, 0, -scale,
                            54 - (x0 + x1) * scale / 2,
                            54 + (y0 + y1) * scale / 2)))
res = app / "android/app/src/main/res"
(res / "drawable/orbit_icon.xml").write_text(f'''<!-- Generated from Icons.blur_circular_rounded; see tool/generate_icons.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="{foreground}" android:pathData="{pen.getCommands()}"/>
</vector>
''')
for directory, monochrome in [("mipmap-anydpi-v26", False), ("mipmap-anydpi-v33", True)]:
    target = res / directory
    target.mkdir(exist_ok=True)
    themed = '\n    <monochrome android:drawable="@drawable/orbit_icon"/>' if monochrome else ''
    (target / "ic_launcher.xml").write_text(f'''<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/launcher_background"/>
    <foreground android:drawable="@drawable/orbit_icon"/>{themed}
</adaptive-icon>
''')
(res / "values/launcher_colors.xml").write_text(f'''<resources>
    <color name="launcher_background">{background}</color>
</resources>
''')

web = app.parents[1] / "web/core-console/public"
web.mkdir(exist_ok=True)
(web / "orbit-icon.svg").write_text(f'''<!-- Google's Material Icons blur_circular_rounded, recolored and padded for Orbit.
Source: https://github.com/google/material-design-icons
License supplied with Flutter's font: https://creativecommons.org/licenses/by/4.0/
Generated by nodes/app/tool/generate_icons.py. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72">
  <rect x="18" y="18" width="72" height="72" rx="16" fill="{background}"/>
  <path fill="{foreground}" d="{pen.getCommands()}"/>
</svg>
''')

# Supersample the glyph before producing each platform's required PNG sizes.
typeface = ImageFont.truetype(str(font_path), 3072)
box = typeface.getbbox(chr(codepoint))
mask = Image.new("L", (box[2] - box[0], box[3] - box[1]))
ImageDraw.Draw(mask).text((-box[0], -box[1]), chr(codepoint), font=typeface, fill=255)
mask = mask.crop(mask.getbbox()).resize((720, 720), Image.Resampling.LANCZOS)
icon = Image.new("RGBA", (1024, 1024))
ImageDraw.Draw(icon).rounded_rectangle((48, 48, 976, 976), radius=208, fill=background)
icon.paste(Image.new("RGBA", mask.size, foreground), (152, 152), mask)
assets = app / "assets"
assets.mkdir(exist_ok=True)
(assets / "MaterialIcons-LICENSE.txt").write_bytes(
    (font_path.parent / "MaterialIcons_LICENSE.txt").read_bytes())
icon.save(assets / "orbit-icon.png")
for density, size in [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)]:
    icon.resize((size, size), Image.Resampling.LANCZOS).save(res / f"mipmap-{density}/ic_launcher.png")
for size in [16, 32, 64, 128, 256, 512, 1024]:
    icon.resize((size, size), Image.Resampling.LANCZOS).save(
        app / f"macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_{size}.png")
icon.save(app / "windows/runner/resources/app_icon.ico",
          sizes=[(size, size) for size in [16, 24, 32, 48, 64, 128, 256]])
print("Generated Android, macOS, Windows and Web icons.")
